"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['CodonOpt.py']
DATA_FILES = ['ylicodontable.txt', 'cthcodontable.txt', 'ecocodontable.txt', 'ctxcodontable.txt', 'codon_opt_gui.ui']
OPTIONS = {'iconfile': 'Codonimg.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
